### ISSUE TITLE
Compatibility with ES 6 and rally 0.9.4

### ISSUE THREAD

**Issue by burandobata** [elastic/rally-eventdata-track#7]
Hi,

I'm trying to use eventdata together with custom ES 6 cluster and rally 0.9.4 and I'm getting following error:
```
[ERROR] Cannot race. ('Could not execute benchmark', TypeError('string indices must be integers',))
```

I've tried with rally 0.9.0 and I'm still getting this. Is this compatible?

**Comment by danielmitterdorfer** [comment]
Thanks for your report @burandobata! This is indeed a backwards-compatibility issue that slipped through the cracks. We have just released Rally 0.10.0. Can you please update (usually that's done with `pip3 install --upgrade esrally`) and retry?

**Comment by burandobata** [comment]
Thanks @danielmitterdorfer,

but it looks like I still have some problem with data generation:
In rally_out.log I have messages like:
```
2018-04-16 12:39:41,839 PID:58270 rally.driver INFO LoadGenerator[6] is executing (no samples).
2018-04-16 12:39:41,945 PID:58276 rally.driver INFO LoadGenerator[12] is executing (no samples).
2018-04-16 12:39:41,958 PID:58266 rally.driver INFO LoadGenerator[2] is executing (no samples).
```

and here is what I have in rally-actor-messages.log:
```
2018-04-16 12:35:47,215 ActorAddr-(T|:50150)/PID:58277 esrally.driver.driver.LoadGenerator WARNING Actor esrally.driver.driver.LoadGenerator @ ActorAddr-(T|:50150) retryable exception on message WakeupMessage(0:00:00.973167, None)
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/thespian/system/actorManager.py", line 155, in _handleOneMessage
    actor_result = self.actorInst.receiveMessage(msg, envelope.sender)

  File "/usr/local/lib/python3.6/site-packages/thespian/actors.py", line 838, in receiveMessage
    r = getattr(klass, methodName)(self, message, sender)

  File "/usr/local/lib/python3.6/site-packages/esrally/driver/driver.py", line 620, in receiveMsg_WakeupMessage
    self.drive()

  File "/usr/local/lib/python3.6/site-packages/esrally/driver/driver.py", line 696, in drive
    schedule = schedule_for(self.track, task_allocation.task, task_allocation.client_index_in_task)

  File "/usr/local/lib/python3.6/site-packages/esrally/driver/driver.py", line 1225, in schedule_for
    params_for_op = track.operation_parameters(current_track, op).partition(client_index, num_clients)

  File "/usr/local/lib/python3.6/site-packages/esrally/track/loader.py", line 222, in operation_parameters
    return params.param_source_for_name(op.param_source, t, op.params)

  File "/usr/local/lib/python3.6/site-packages/esrally/track/params.py", line 57, in param_source_for_name
    return param_source(track, params)

  File "/Users/maslanm/.rally/benchmarks/tracks/eventdata/eventdata/parameter_sources/elasticlogs_bulk_source.py", line 71, in __init__
    self._params['type'] = self._indices[0].types[0].name

AttributeError: 'str' object has no attribute 'name'
```

I've even tried to remove whole installation of rally and reinstall 0.10 from scratch, but I still have the same.

**Comment by danielmitterdorfer** [comment]
I've pushed a fix for that and verified locally that the default challenge (`append-no-conflicts) works with the latest version of Rally. Can you please retry?

**Comment by burandobata** [comment]
This two fixes have helped, append-no-conflict is working fine. I will try remaining challenges also.

Thank you!

**Comment by danielmitterdorfer** [comment]
Thanks for your report and double-checking! Closing as fixed.
